export const ARUBA_AREAS = [
  "Babijn",
  "Bringamosa",
  "Bubali",
  "Cunucu Abao",
  "Dakota",
  "Eagle Beach",
  "Madiki",
  "Malmok",
  "Noord",
  "Oranjestad",
  "Palm Beach",
  "Paradera",
  "Piedra Plat",
  "Ponton",
  "Pos Chikito",
  "San Nicolas",
  "Santa Cruz",
  "Savaneta",
  "Sero Colorado",
  "Seroe Blanco",
  "Tanki Leendert",
  "Other",
];
