export interface PhoneCountry {
  code: string;   // e.g. "+297"
  iso: string;    // e.g. "AW"
  name: string;   // e.g. "Aruba"
  flag: string;   // emoji flag
}

// Aruba first, then pinned favourites, then world A–Z
export const PHONE_COUNTRIES: PhoneCountry[] = [
  { code: "+297",  iso: "AW", name: "Aruba",                    flag: "🇦🇼" },
  { code: "+599",  iso: "BQ", name: "Bonaire",                  flag: "🇧🇶" },
  { code: "+1",    iso: "CA", name: "Canada",                   flag: "🇨🇦" },
  { code: "+57",   iso: "CO", name: "Colombia",                 flag: "🇨🇴" },
  { code: "+599",  iso: "CW", name: "Curaçao",                  flag: "🇨🇼" },
  { code: "+31",   iso: "NL", name: "Netherlands",              flag: "🇳🇱" },
  { code: "+58",   iso: "VE", name: "Venezuela",                flag: "🇻🇪" },
  { code: "+1",    iso: "US", name: "USA",                      flag: "🇺🇸" },
  { code: "",      iso: "––", name: "──────────────",           flag: "" },
  // ── rest A–Z ──────────────────────────────────────────────────────────────
  // Caribbean & nearby
  { code: "+1268", iso: "AG", name: "Antigua & Barbuda",        flag: "🇦🇬" },
  { code: "+1264", iso: "AI", name: "Anguilla",                 flag: "🇦🇮" },
  { code: "+1242", iso: "BS", name: "Bahamas",                  flag: "🇧🇸" },
  { code: "+1246", iso: "BB", name: "Barbados",                 flag: "🇧🇧" },
  { code: "+501",  iso: "BZ", name: "Belize",                   flag: "🇧🇿" },
  { code: "+1441", iso: "BM", name: "Bermuda",                  flag: "🇧🇲" },
  { code: "+1284", iso: "VG", name: "British Virgin Islands",   flag: "🇻🇬" },
  { code: "+1345", iso: "KY", name: "Cayman Islands",           flag: "🇰🇾" },
  { code: "+506",  iso: "CR", name: "Costa Rica",               flag: "🇨🇷" },
  { code: "+53",   iso: "CU", name: "Cuba",                     flag: "🇨🇺" },
  { code: "+1767", iso: "DM", name: "Dominica",                 flag: "🇩🇲" },
  { code: "+1809", iso: "DO", name: "Dominican Republic",       flag: "🇩🇴" },
  { code: "+503",  iso: "SV", name: "El Salvador",              flag: "🇸🇻" },
  { code: "+590",  iso: "GP", name: "Guadeloupe",               flag: "🇬🇵" },
  { code: "+502",  iso: "GT", name: "Guatemala",                flag: "🇬🇹" },
  { code: "+509",  iso: "HT", name: "Haiti",                    flag: "🇭🇹" },
  { code: "+504",  iso: "HN", name: "Honduras",                 flag: "🇭🇳" },
  { code: "+1876", iso: "JM", name: "Jamaica",                  flag: "🇯🇲" },
  { code: "+596",  iso: "MQ", name: "Martinique",               flag: "🇲🇶" },
  { code: "+52",   iso: "MX", name: "Mexico",                   flag: "🇲🇽" },
  { code: "+1664", iso: "MS", name: "Montserrat",               flag: "🇲🇸" },
  { code: "+505",  iso: "NI", name: "Nicaragua",                flag: "🇳🇮" },
  { code: "+507",  iso: "PA", name: "Panama",                   flag: "🇵🇦" },
  { code: "+1787", iso: "PR", name: "Puerto Rico",              flag: "🇵🇷" },
  { code: "+1869", iso: "KN", name: "Saint Kitts & Nevis",      flag: "🇰🇳" },
  { code: "+1758", iso: "LC", name: "Saint Lucia",              flag: "🇱🇨" },
  { code: "+590",  iso: "MF", name: "Saint Martin",             flag: "🇲🇫" },
  { code: "+1784", iso: "VC", name: "St Vincent & Grenadines",  flag: "🇻🇨" },
  { code: "+1721", iso: "SX", name: "Sint Maarten",             flag: "🇸🇽" },
  { code: "+1868", iso: "TT", name: "Trinidad & Tobago",        flag: "🇹🇹" },
  { code: "+1649", iso: "TC", name: "Turks & Caicos",           flag: "🇹🇨" },
  { code: "+1340", iso: "VI", name: "US Virgin Islands",        flag: "🇻🇮" },
  // Europe
  { code: "+355",  iso: "AL", name: "Albania",                  flag: "🇦🇱" },
  { code: "+43",   iso: "AT", name: "Austria",                  flag: "🇦🇹" },
  { code: "+32",   iso: "BE", name: "Belgium",                  flag: "🇧🇪" },
  { code: "+387",  iso: "BA", name: "Bosnia & Herzegovina",     flag: "🇧🇦" },
  { code: "+359",  iso: "BG", name: "Bulgaria",                 flag: "🇧🇬" },
  { code: "+385",  iso: "HR", name: "Croatia",                  flag: "🇭🇷" },
  { code: "+357",  iso: "CY", name: "Cyprus",                   flag: "🇨🇾" },
  { code: "+420",  iso: "CZ", name: "Czech Republic",           flag: "🇨🇿" },
  { code: "+45",   iso: "DK", name: "Denmark",                  flag: "🇩🇰" },
  { code: "+372",  iso: "EE", name: "Estonia",                  flag: "🇪🇪" },
  { code: "+358",  iso: "FI", name: "Finland",                  flag: "🇫🇮" },
  { code: "+33",   iso: "FR", name: "France",                   flag: "🇫🇷" },
  { code: "+49",   iso: "DE", name: "Germany",                  flag: "🇩🇪" },
  { code: "+30",   iso: "GR", name: "Greece",                   flag: "🇬🇷" },
  { code: "+36",   iso: "HU", name: "Hungary",                  flag: "🇭🇺" },
  { code: "+354",  iso: "IS", name: "Iceland",                  flag: "🇮🇸" },
  { code: "+353",  iso: "IE", name: "Ireland",                  flag: "🇮🇪" },
  { code: "+39",   iso: "IT", name: "Italy",                    flag: "🇮🇹" },
  { code: "+371",  iso: "LV", name: "Latvia",                   flag: "🇱🇻" },
  { code: "+370",  iso: "LT", name: "Lithuania",                flag: "🇱🇹" },
  { code: "+352",  iso: "LU", name: "Luxembourg",               flag: "🇱🇺" },
  { code: "+356",  iso: "MT", name: "Malta",                    flag: "🇲🇹" },
  { code: "+373",  iso: "MD", name: "Moldova",                  flag: "🇲🇩" },
  { code: "+382",  iso: "ME", name: "Montenegro",               flag: "🇲🇪" },
  { code: "+389",  iso: "MK", name: "North Macedonia",          flag: "🇲🇰" },
  { code: "+47",   iso: "NO", name: "Norway",                   flag: "🇳🇴" },
  { code: "+48",   iso: "PL", name: "Poland",                   flag: "🇵🇱" },
  { code: "+351",  iso: "PT", name: "Portugal",                 flag: "🇵🇹" },
  { code: "+40",   iso: "RO", name: "Romania",                  flag: "🇷🇴" },
  { code: "+7",    iso: "RU", name: "Russia",                   flag: "🇷🇺" },
  { code: "+381",  iso: "RS", name: "Serbia",                   flag: "🇷🇸" },
  { code: "+421",  iso: "SK", name: "Slovakia",                 flag: "🇸🇰" },
  { code: "+386",  iso: "SI", name: "Slovenia",                 flag: "🇸🇮" },
  { code: "+34",   iso: "ES", name: "Spain",                    flag: "🇪🇸" },
  { code: "+46",   iso: "SE", name: "Sweden",                   flag: "🇸🇪" },
  { code: "+41",   iso: "CH", name: "Switzerland",              flag: "🇨🇭" },
  { code: "+380",  iso: "UA", name: "Ukraine",                  flag: "🇺🇦" },
  { code: "+44",   iso: "GB", name: "United Kingdom",           flag: "🇬🇧" },
  // South America
  { code: "+54",   iso: "AR", name: "Argentina",                flag: "🇦🇷" },
  { code: "+591",  iso: "BO", name: "Bolivia",                  flag: "🇧🇴" },
  { code: "+55",   iso: "BR", name: "Brazil",                   flag: "🇧🇷" },
  { code: "+56",   iso: "CL", name: "Chile",                    flag: "🇨🇱" },
  { code: "+593",  iso: "EC", name: "Ecuador",                  flag: "🇪🇨" },
  { code: "+592",  iso: "GY", name: "Guyana",                   flag: "🇬🇾" },
  { code: "+595",  iso: "PY", name: "Paraguay",                 flag: "🇵🇾" },
  { code: "+51",   iso: "PE", name: "Peru",                     flag: "🇵🇪" },
  { code: "+597",  iso: "SR", name: "Suriname",                 flag: "🇸🇷" },
  { code: "+598",  iso: "UY", name: "Uruguay",                  flag: "🇺🇾" },
  // Africa
  { code: "+213",  iso: "DZ", name: "Algeria",                  flag: "🇩🇿" },
  { code: "+244",  iso: "AO", name: "Angola",                   flag: "🇦🇴" },
  { code: "+237",  iso: "CM", name: "Cameroon",                 flag: "🇨🇲" },
  { code: "+20",   iso: "EG", name: "Egypt",                    flag: "🇪🇬" },
  { code: "+251",  iso: "ET", name: "Ethiopia",                 flag: "🇪🇹" },
  { code: "+233",  iso: "GH", name: "Ghana",                    flag: "🇬🇭" },
  { code: "+254",  iso: "KE", name: "Kenya",                    flag: "🇰🇪" },
  { code: "+212",  iso: "MA", name: "Morocco",                  flag: "🇲🇦" },
  { code: "+234",  iso: "NG", name: "Nigeria",                  flag: "🇳🇬" },
  { code: "+27",   iso: "ZA", name: "South Africa",             flag: "🇿🇦" },
  { code: "+255",  iso: "TZ", name: "Tanzania",                 flag: "🇹🇿" },
  { code: "+256",  iso: "UG", name: "Uganda",                   flag: "🇺🇬" },
  // Middle East
  { code: "+973",  iso: "BH", name: "Bahrain",                  flag: "🇧🇭" },
  { code: "+964",  iso: "IQ", name: "Iraq",                     flag: "🇮🇶" },
  { code: "+972",  iso: "IL", name: "Israel",                   flag: "🇮🇱" },
  { code: "+962",  iso: "JO", name: "Jordan",                   flag: "🇯🇴" },
  { code: "+965",  iso: "KW", name: "Kuwait",                   flag: "🇰🇼" },
  { code: "+961",  iso: "LB", name: "Lebanon",                  flag: "🇱🇧" },
  { code: "+968",  iso: "OM", name: "Oman",                     flag: "🇴🇲" },
  { code: "+974",  iso: "QA", name: "Qatar",                    flag: "🇶🇦" },
  { code: "+966",  iso: "SA", name: "Saudi Arabia",             flag: "🇸🇦" },
  { code: "+971",  iso: "AE", name: "UAE",                      flag: "🇦🇪" },
  { code: "+967",  iso: "YE", name: "Yemen",                    flag: "🇾🇪" },
  // Asia
  { code: "+93",   iso: "AF", name: "Afghanistan",              flag: "🇦🇫" },
  { code: "+880",  iso: "BD", name: "Bangladesh",               flag: "🇧🇩" },
  { code: "+855",  iso: "KH", name: "Cambodia",                 flag: "🇰🇭" },
  { code: "+86",   iso: "CN", name: "China",                    flag: "🇨🇳" },
  { code: "+852",  iso: "HK", name: "Hong Kong",                flag: "🇭🇰" },
  { code: "+91",   iso: "IN", name: "India",                    flag: "🇮🇳" },
  { code: "+62",   iso: "ID", name: "Indonesia",                flag: "🇮🇩" },
  { code: "+81",   iso: "JP", name: "Japan",                    flag: "🇯🇵" },
  { code: "+82",   iso: "KR", name: "South Korea",              flag: "🇰🇷" },
  { code: "+60",   iso: "MY", name: "Malaysia",                 flag: "🇲🇾" },
  { code: "+960",  iso: "MV", name: "Maldives",                 flag: "🇲🇻" },
  { code: "+976",  iso: "MN", name: "Mongolia",                 flag: "🇲🇳" },
  { code: "+95",   iso: "MM", name: "Myanmar",                  flag: "🇲🇲" },
  { code: "+977",  iso: "NP", name: "Nepal",                    flag: "🇳🇵" },
  { code: "+92",   iso: "PK", name: "Pakistan",                 flag: "🇵🇰" },
  { code: "+63",   iso: "PH", name: "Philippines",              flag: "🇵🇭" },
  { code: "+65",   iso: "SG", name: "Singapore",                flag: "🇸🇬" },
  { code: "+94",   iso: "LK", name: "Sri Lanka",                flag: "🇱🇰" },
  { code: "+886",  iso: "TW", name: "Taiwan",                   flag: "🇹🇼" },
  { code: "+66",   iso: "TH", name: "Thailand",                 flag: "🇹🇭" },
  { code: "+84",   iso: "VN", name: "Vietnam",                  flag: "🇻🇳" },
  // Oceania
  { code: "+61",   iso: "AU", name: "Australia",                flag: "🇦🇺" },
  { code: "+679",  iso: "FJ", name: "Fiji",                     flag: "🇫🇯" },
  { code: "+64",   iso: "NZ", name: "New Zealand",              flag: "🇳🇿" },
];

export const DEFAULT_COUNTRY = PHONE_COUNTRIES[0]; // Aruba +297

/** Split a stored phone string like "+297 560 0000" into { country, number } */
export function splitPhone(value: string): { country: PhoneCountry; number: string } {
  const sorted = [...PHONE_COUNTRIES].sort((a, b) => b.code.length - a.code.length);
  for (const c of sorted) {
    if (value.startsWith(c.code)) {
      return { country: c, number: value.slice(c.code.length).trim() };
    }
  }
  return { country: DEFAULT_COUNTRY, number: value };
}
